### PR TITLE
remove inst_suseconfig call

### PR DESCRIPTION
**Pull request by jsuchome**
(plese adapt the UI and all SuSEconfig\* stuff here)

### CODE REVIEW

**Comment by kobliha** [comment]
You were faster than I could do that :)

**Comment by kobliha** [comment]
Sorry but what about the changes file?

**Comment by jsuchome** [comment]
that's up to you, after all suseconfig stuff goes away

this commit is more a reminder

**Comment by jsuchome** [comment]
I mean, for other modules, I'm doing whole pack myself, but here is just too much of code I do not understand so I leave it up to maitnainer

**Pull request merged**
